### ISSUE TITLE
Protection doesn't work when clicking Q

### ISSUE THREAD

**Issue by Sup33r** [Oscar0159/MapRights#10]
If you try to copy a protected map, it doesn't work (as it should). But if you in the interface click Q instead, it gets dropped on the ground, and copied. Works in the Cartography table and Craftingtable (and any place that uses the InventoryClickEvent listener.

**Comment by Sup33r** [comment]
I opened a pull request which fixed this, and also that you could use the hotbar keys to move it. #11

**Comment by Oscar0159** [comment]
PR mregerd!
Your pr comments are correct. I hadn't considered that. I'll remove that entire block(action check) of code in a future release.
